# Binds operator-valid-subscription policy to all namespaces (ClusterServiceVersion create/update).
# No paramRef: only annotation presence and allowed values are checked.
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: operator-valid-subscription-binding
spec:
  policyName: operator-valid-subscription
  validationActions: ["Deny"]
  matchResources:
    resourceRules:
      - apiGroups: ["operators.coreos.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterserviceversions"]
