# Binds operator-subscription-matches-cluster policy and passes allowed subscription list via ConfigMap.
# ConfigMap (cluster-subscription-type) must have keys validSubscription.0, validSubscription.1, ...
# with values being allowed subscription names. Apply one of config/cluster-subscription-*.yaml or create your own list.
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: operator-subscription-matches-cluster-binding
spec:
  policyName: operator-subscription-matches-cluster
  validationActions: ["Deny"]
  paramRef:
    name: cluster-subscription-type
    namespace: operator-subscription
    parameterNotFoundAction: Allow
  matchResources:
    resourceRules:
      - apiGroups: ["operators.coreos.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterserviceversions"]
