# ValidatingAdmissionPolicy: When a list of allowed subscription names is provided
# via ConfigMap param, the CSV's valid-subscription annotation must include at
# least one of those names.
#
# ConfigMap must have keys validSubscription.0, validSubscription.1, ... with
# values being the allowed subscription names (e.g. "OpenShift Kubernetes Engine",
# "Red Hat Trusted Profile Analyzer"). The list is the set of subscriptions
# allowed for this cluster.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: operator-subscription-matches-cluster
  annotations:
    description: "Ensures CSV valid-subscription includes at least one subscription from the cluster's allowed list (ConfigMap)."
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConditions:
    - name: is-csv
      expression: "object.kind == 'ClusterServiceVersion'"
  validations:
    # Allow if: no param/list, no validSubscription.* keys, no CSV annotation, valid-subscription is "none", or CSV lists at least one allowed subscription.
    - expression: |
        params == null || params.data == null || size(params.data) == 0 ||
        !params.data.exists(k, k.startsWith("validSubscription.")) ||
        !has(object.metadata) || !has(object.metadata.annotations) || !("operators.openshift.io/valid-subscription" in object.metadata.annotations) ||
        object.metadata.annotations["operators.openshift.io/valid-subscription"] == "none" ||
        object.metadata.annotations["operators.openshift.io/valid-subscription"].contains('"none"') ||
        params.data.exists(k, k.startsWith("validSubscription.") && object.metadata.annotations["operators.openshift.io/valid-subscription"].contains('"' + params.data[k] + '"'))
      message: "Operator valid-subscription does not include any subscription allowed for this cluster (see ConfigMap validSubscription.*)."
      reason: Forbidden
  matchConstraints:
    resourceRules:
      - apiGroups: ["operators.coreos.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterserviceversions"]
